trigger:
  branches:
    include:
      - main

pool:
  name: 'myAzurePool'  # Use your self-hosted agent pool

stages:
  # Build Stage
  - stage: Build
    jobs:
      - job: BuildJob
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '14.x'
            displayName: 'Set up Node.js'

          - script: |
              echo "Installing dependencies..."
              npm install
            displayName: 'Install Dependencies'

          - script: |
              echo "Compiling source code..."
              npm run build
            displayName: 'Build the Code'

          - task: PublishBuildArtifacts@1
            inputs:
              pathtoPublish: '$(Build.SourcesDirectory)/dist'
              artifactName: 'build-artifacts'
              publishLocation: 'Container'
            displayName: 'Publish Build Artifacts'

  # Test Stage
  - stage: Test
    dependsOn: Build
    jobs:
      - job: TestJob
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '14.x'
            displayName: 'Set up Node.js'

          - script: |
              echo "Installing dependencies..."
              npm install
            displayName: 'Install Dependencies'

          - script: |
              echo "Running unit tests..."
              npm test
            displayName: 'Run Unit Tests'

          - script: |
              echo "Running code coverage..."
              npm run coverage
            displayName: 'Code Coverage'

          - script: |
              echo "Running code quality checks..."
              npm run lint
            displayName: 'Code Quality Analysis'

  # Deploy Stage
  - stage: Deploy
    dependsOn: Test
    jobs:
      - job: DeployJob
        steps:
          - script: |
              echo "Deploying application to staging environment..."
              # Example: Replace with actual deployment command
              ./deploy.sh staging
            displayName: 'Deploy to Staging Environment'

          - script: |
              echo "Deployment to staging environment successful!"
            displayName: 'Deployment Success'
